BEGIN;

ALTER TABLE public.edubite_inspiration_quotes
  ADD COLUMN IF NOT EXISTS content_key text,
  ADD COLUMN IF NOT EXISTS category text NOT NULL DEFAULT 'General';

UPDATE public.edubite_inspiration_quotes
SET content_key = 'legacy-' || id::text
WHERE content_key IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS edubite_inspiration_quotes_content_key_idx
  ON public.edubite_inspiration_quotes (content_key);

CREATE INDEX IF NOT EXISTS edubite_inspiration_quotes_category_idx
  ON public.edubite_inspiration_quotes (category);

WITH catalog(content_key, category, quote, sort_order) AS (
  VALUES
    ('pcm-motivation-001', 'Discipline and Consistency', 'A chapter studied daily becomes a rank earned quietly.', 0),
    ('pcm-motivation-002', 'Discipline and Consistency', 'Consistency turns difficult subjects into familiar territory.', 1),
    ('pcm-motivation-003', 'Discipline and Consistency', 'You do not need ten perfect hours; you need few honest hours every day.', 2),
    ('pcm-motivation-004', 'Discipline and Consistency', 'Small revisions repeated often build stronger memory than last-minute panic.', 3),
    ('pcm-motivation-005', 'Discipline and Consistency', 'Discipline begins when motivation ends.', 4),
    ('pcm-motivation-006', 'Discipline and Consistency', 'A timetable works only when you respect the time written on it.', 5),
    ('pcm-motivation-007', 'Discipline and Consistency', 'The student who returns to the problem eventually becomes stronger than the problem.', 6),
    ('pcm-motivation-008', 'Discipline and Consistency', 'Daily effort is compound interest for your future.', 7),
    ('pcm-motivation-009', 'Discipline and Consistency', 'Do not count how many pages remain; complete the page in front of you.', 8),
    ('pcm-motivation-010', 'Discipline and Consistency', 'A strong result in the form of a streak is usually the visible part of an invisible routine.', 9),
    ('pcm-motivation-011', 'Discipline and Consistency', 'Study at the same time each day until focus becomes a habit.', 10),
    ('pcm-motivation-012', 'Discipline and Consistency', 'Missing one day is a mistake; missing many days becomes a pattern.', 11),
    ('pcm-motivation-013', 'Discipline and Consistency', 'Progress grows when excuses shrink. Make sure you show up.', 12),
    ('pcm-motivation-014', 'Discipline and Consistency', 'Your routine should protect your goals from your moods.', 13),
    ('pcm-motivation-015', 'Discipline and Consistency', 'The best academic comeback begins with today’s first focused hour.', 14),
    ('pcm-motivation-016', 'Learning and Understanding', 'Do not memorise what you can understand.', 15),
    ('pcm-motivation-017', 'Learning and Understanding', 'A formula becomes powerful only when you know why it works.', 16),
    ('pcm-motivation-018', 'Learning and Understanding', 'Understanding reduces the burden that memory has to carry.', 17),
    ('pcm-motivation-019', 'Learning and Understanding', 'When a concept feels confusing, break it into smaller chunks.', 18),
    ('pcm-motivation-020', 'Learning and Understanding', 'The ability to explain simply is proof that you understand deeply.', 19),
    ('pcm-motivation-021', 'Learning and Understanding', 'Every difficult chapter is a collection of simpler ideas placed together.', 20),
    ('pcm-motivation-022', 'Learning and Understanding', 'Read less passively and think more actively. Do not read science like a novel', 21),
    ('pcm-motivation-023', 'Learning and Understanding', 'A solved example teaches a method; an unsolved question tests whether the method is yours.', 22),
    ('pcm-motivation-024', 'Learning and Understanding', 'Knowledge becomes permanent when you connect it to something you already know.', 23),
    ('pcm-motivation-025', 'Learning and Understanding', 'Do not underline or highlight everything; identify what actually matters.', 24),
    ('pcm-motivation-026', 'Learning and Understanding', 'The mind remembers relationships better than isolated facts.', 25),
    ('pcm-motivation-027', 'Learning and Understanding', 'Understanding is slower than memorising, but it lasts much longer.', 26),
    ('pcm-motivation-028', 'Learning and Understanding', 'Study the concept until the formula feels inevitable.', 27),
    ('pcm-motivation-029', 'Learning and Understanding', 'Real learning begins when you stop copying and start questioning.', 28),
    ('pcm-motivation-030', 'Mathematics', 'Mathematics rewards patience more than speed while learning something new.', 29),
    ('pcm-motivation-031', 'Mathematics', 'Every long solution is built from short, correct steps. Move step-by-step', 30),
    ('pcm-motivation-032', 'Mathematics', 'Practise until you recognise the structure, not merely the question.', 31),
    ('pcm-motivation-033', 'Mathematics', 'If the answer looks impossible, check the assumption before checking the arithmetic.', 32),
    ('pcm-motivation-034', 'Mathematics', 'The shortest solution is not always the best learning solution.', 33),
    ('pcm-motivation-035', 'Mathematics', 'A theorem remembered without its conditions is only half remembered.', 34),
    ('pcm-motivation-036', 'Mathematics', 'Mathematical confidence comes from solving, not from watching someone else solve.', 35),
    ('pcm-motivation-037', 'Mathematics', 'When stuck, rewrite the problem in a different form.', 36),
    ('pcm-motivation-038', 'Mathematics', 'Accuracy first, speed later. Finally build accuracy with speed', 37),
    ('pcm-motivation-039', 'Mathematics', 'The habit of checking your answer is as important as finding it.', 38),
    ('pcm-motivation-040', 'Physics', 'Physics is not a collection of formulae; it is a way of seeing causes and effects.', 39),
    ('pcm-motivation-041', 'Physics', 'A correct free-body diagram can solve half the problem.', 40),
    ('pcm-motivation-042', 'Physics', 'Every numerical becomes easier when the physical situation is clear.', 41),
    ('pcm-motivation-043', 'Physics', 'Before calculating, predict whether the answer should increase, decrease or remain unchanged.', 42),
    ('pcm-motivation-044', 'Physics', 'A formula tells you the relationship; reasoning tells you when to use it.', 43),
    ('pcm-motivation-045', 'Physics', 'Do not substitute numbers before understanding the variables.', 44),
    ('pcm-motivation-046', 'Physics', 'If your answer violates common sense, recheck your model.', 45),
    ('pcm-motivation-047', 'Physics', 'Physics becomes beautiful when equations match real behaviour.', 46),
    ('pcm-motivation-048', 'Physics', 'The best problem solvers visualise first and calculate second.', 47),
    ('pcm-motivation-049', 'Chemistry', 'Chemistry becomes easier when reactions are understood as patterns, not isolated facts.', 48),
    ('pcm-motivation-050', 'Chemistry', 'The periodic table is a map, not a memory test. Learn why it is built in a certain way', 49),
    ('pcm-motivation-051', 'Chemistry', 'Learn trends with reasons, and exceptions will become easier to remember.', 50),
    ('pcm-motivation-052', 'Chemistry', 'In organic chemistry, structure often predicts behaviour.', 51),
    ('pcm-motivation-053', 'Chemistry', 'Never ignore the state, charge or conditions written in a reaction.', 52),
    ('pcm-motivation-054', 'Chemistry', 'The mole connects the invisible world of particles to measurable quantities.', 53),
    ('pcm-motivation-055', 'Chemistry', 'Organic chemistry becomes manageable when you follow electron movement.', 54),
    ('pcm-motivation-056', 'Chemistry', 'Physical chemistry improves when concepts and calculations are studied together.', 55),
    ('pcm-motivation-057', 'Chemistry', 'Inorganic chemistry needs repeated revision because familiarity creates recall.', 56),
    ('pcm-motivation-058', 'Chemistry', 'A reaction remembered without its conditions is an incomplete reaction.', 57),
    ('pcm-motivation-059', 'Chemistry', 'Acids, bases and equilibria become simpler when you think in terms of competing processes.', 58),
    ('pcm-motivation-060', 'Chemistry', 'Observation, explanation and equation are the three layers of good chemistry.', 59),
    ('pcm-motivation-061', 'Exams and Performance', 'Your preparation should make the exam feel familiar, not frightening.', 60),
    ('pcm-motivation-062', 'Exams and Performance', 'Mock tests reveal weaknesses before the final exam does.', 61),
    ('pcm-motivation-063', 'Exams and Performance', 'Do not only count marks; study the reason behind every lost mark.', 62),
    ('pcm-motivation-064', 'Exams and Performance', 'Time management in an exam begins with time management during preparation.', 63),
    ('pcm-motivation-065', 'Exams and Performance', 'Attempt the paper with calm strategy, not emotional speed.', 64),
    ('pcm-motivation-066', 'Exams and Performance', 'Read the question twice before answering it once.', 65),
    ('pcm-motivation-067', 'Exams and Performance', 'A few difficult questions are not a reason to lose confidence in the entire paper. Skip them and continue rather than getting stuck.', 66),
    ('pcm-motivation-068', 'Exams and Performance', 'Secure the questions you know before wrestling with the questions you do not.', 67),
    ('pcm-motivation-069', 'Exams and Performance', 'Revision should become more selective as the exam gets closer.', 68),
    ('pcm-motivation-070', 'Exams and Performance', 'Sleep before an exam is part of preparation, not a break from it. Good sleep prepares you to excel', 69),
    ('pcm-motivation-071', 'Exams and Performance', 'One poor test is feedback, not a prediction. So, keep taking mock tests to perfect yourself', 70),
    ('pcm-motivation-072', 'Exams and Performance', 'Compete with yesterday’s version of yourself before competing with anyone else.', 71),
    ('pcm-motivation-073', 'Exams and Performance', 'Marks measure performance on a day; habits shape performance for years.', 72),
    ('pcm-motivation-074', 'Exams and Performance', 'Study not only to clear the exam, but to become capable of solving harder problems in life.', 73),
    ('pcm-motivation-075', 'Exams and Performance', 'Plan and pace your revisions well before an exam.  Good revision can uplift your marks significantly.', 74),
    ('pcm-motivation-076', 'Exams and Performance', 'An exam does not reward what you planned to study; it rewards what you can recall and apply.', 75),
    ('pcm-motivation-077', 'Exams and Performance', 'Performance improves when preparation becomes measurable.', 76),
    ('pcm-motivation-078', 'Exams and Performance', 'Every mock test is a rehearsal for calmness, accuracy and better decisions.', 77),
    ('pcm-motivation-079', 'Exams and Performance', 'Marks increase when mistakes are analysed instead of merely counted.', 78),
    ('pcm-motivation-080', 'Exams and Performance', 'The purpose of a test is not only to judge you, but to show you what to strengthen.', 79),
    ('pcm-motivation-081', 'Exams and Performance', 'A difficult paper challenges every student; your response determines your advantage.', 80),
    ('pcm-motivation-082', 'Exams and Performance', 'Strong performance is built by practising under the same limits you will face in the exam.', 81),
    ('pcm-motivation-083', 'Exams and Performance', 'Do not let one unfamiliar question disturb the questions you already know. Just move on.', 82),
    ('pcm-motivation-084', 'Exams and Performance', 'Your score improves when every lost mark teaches you a specific lesson.', 83),
    ('pcm-motivation-085', 'Exams and Performance', 'Exams test knowledge, but they also test judgement, patience and time management.', 84),
    ('pcm-motivation-086', 'Exams and Performance', 'A question left unread can cost as many marks as a question answered incorrectly.', 85),
    ('pcm-motivation-087', 'Exams and Performance', 'Good preparation makes difficult questions manageable and easy questions dependable.', 86),
    ('pcm-motivation-088', 'Exams and Performance', 'Attempting every question is not always wise; selecting the right order often matters more.', 87),
    ('pcm-motivation-089', 'Exams and Performance', 'Do not measure performance only by marks; measure accuracy, speed and error reduction.', 88),
    ('pcm-motivation-090', 'Exams and Performance', 'The student who reviews the paper learns more than the student who only celebrates the score.', 89),
    ('pcm-motivation-091', 'Exams and Performance', 'In an examination, clear thinking is worth more than hurried remembering.', 90),
    ('pcm-motivation-092', 'Exams and Performance', 'Improvement begins when you stop saying ‘careless mistake’ and identify the exact cause.', 91),
    ('pcm-motivation-093', 'Exams and Performance', 'A high score is usually the result of hundreds of small corrections. So practice regularly.', 92),
    ('pcm-motivation-094', 'Exams and Performance', 'Your final result is shaped by how seriously you treat ordinary practice tests.', 93),
    ('pcm-motivation-095', 'Discipline and Consistency', 'Discipline is choosing the chapter that needs attention, not the chapter that feels comfortable.', 94),
    ('pcm-motivation-096', 'Discipline and Consistency', 'Consistency makes ordinary effort produce extraordinary results.', 95),
    ('pcm-motivation-097', 'Discipline and Consistency', 'A realistic timetable followed daily is better than a perfect timetable followed occasionally.', 96),
    ('pcm-motivation-098', 'Discipline and Consistency', 'The strongest study habit is beginning on time, even when you do not feel ready.', 97),
    ('pcm-motivation-099', 'Discipline and Consistency', 'Daily revision prevents yesterday’s learning from becoming tomorrow’s forgotten topic.', 98),
    ('pcm-motivation-100', 'Discipline and Consistency', 'A missed target should lead to adjustment, not abandonment.', 99),
    ('pcm-motivation-101', 'Discipline and Consistency', 'Studying for one hour daily builds more strength than studying seven hours once a week.', 100),
    ('pcm-motivation-102', 'Discipline and Consistency', 'Discipline is the bridge between knowing what to do and actually doing it.', 101),
    ('pcm-motivation-103', 'Discipline and Consistency', 'Complete today’s task before adding tomorrow’s ambition.', 102),
    ('pcm-motivation-104', 'Discipline and Consistency', 'Your habits are writing your result long before the examination begins.', 103),
    ('pcm-motivation-105', 'Discipline and Consistency', 'Regular practice turns difficult calculations into familiar movements.', 104),
    ('pcm-motivation-106', 'Discipline and Consistency', 'Consistency is not doing everything every day; it is doing the important things repeatedly.', 105),
    ('pcm-motivation-107', 'Discipline and Consistency', 'Protect your study time as carefully as you protect an important appointment.', 106),
    ('pcm-motivation-108', 'Discipline and Consistency', 'When concentration is weak, reduce the distraction—not the goal.', 107),
    ('pcm-motivation-109', 'Discipline and Consistency', 'The first disciplined decision of the day makes the next one easier.', 108),
    ('pcm-motivation-110', 'Discipline and Consistency', 'A routine becomes powerful when you follow it even without supervision.', 109),
    ('pcm-motivation-111', 'Discipline and Consistency', 'Progress becomes visible only after consistency has been invisible for a long time.', 110),
    ('pcm-motivation-112', 'Discipline and Consistency', 'Do not wait for a free day to do something important; create a focused hour.', 111),
    ('pcm-motivation-113', 'Discipline and Consistency', 'The discipline to revise small portions daily defeats the pressure of revising everything later.', 112),
    ('pcm-motivation-114', 'Learning and Understanding', 'Learning begins when you ask why an answer is correct, not only which answer is correct.', 113),
    ('pcm-motivation-115', 'Learning and Understanding', 'A concept understood from first principles can solve many unfamiliar questions.', 114),
    ('pcm-motivation-116', 'Learning and Understanding', 'Do not collect formulas without learning the situations in which they apply.', 115),
    ('pcm-motivation-117', 'Learning and Understanding', 'The mind learns deeply when it compares, connects and explains.', 116),
    ('pcm-motivation-118', 'Learning and Understanding', 'Reading creates familiarity; solving creates capability. Numeric problems clear your concepts', 117),
    ('pcm-motivation-119', 'Learning and Understanding', 'A doubt asked today can prevent ten errors tomorrow. Assumptions make you pay repeatedly', 118),
    ('pcm-motivation-120', 'Learning and Understanding', 'A difficult concept becomes easier when divided into definitions, relationships and examples.', 119),
    ('pcm-motivation-121', 'Learning and Understanding', 'Memorisation stores information; understanding shows you how to use it.', 120),
    ('pcm-motivation-122', 'Learning and Understanding', 'The best notes do not copy the textbook; they organise your thinking.', 121),
    ('pcm-motivation-123', 'Learning and Understanding', 'Whenever you learn a formula, learn its variables, units, assumptions and limitations.', 122),
    ('pcm-motivation-124', 'Learning and Understanding', 'Mistakes are useful when they expose the exact point where your reasoning changed direction.', 123),
    ('pcm-motivation-125', 'Learning and Understanding', 'Do not rush past a solved question until you can explain every step.', 124),
    ('pcm-motivation-126', 'Learning and Understanding', 'Learning is complete only when you can recognise the concept in a new form.', 125),
    ('pcm-motivation-127', 'Learning and Understanding', 'A diagram can turn an abstract idea into a solvable problem.', 126),
    ('pcm-motivation-128', 'Learning and Understanding', 'Questions strengthen memory more effectively than repeated passive reading.', 127),
    ('pcm-motivation-129', 'Learning and Understanding', 'If a chapter feels overwhelming, begin with its vocabulary and basic relationships.', 128),
    ('pcm-motivation-130', 'Learning and Understanding', 'Deep understanding reduces both revision time and exam anxiety.', 129),
    ('pcm-motivation-131', 'Learning and Understanding', 'The goal is not to remember the page; it is to reconstruct the idea.', 130),
    ('pcm-motivation-132', 'Speed, Accuracy and Stamina', 'Speed without accuracy creates more work, not more marks.', 131),
    ('pcm-motivation-133', 'Speed, Accuracy and Stamina', 'Accuracy must become stable before speed becomes useful.', 132),
    ('pcm-motivation-134', 'Speed, Accuracy and Stamina', 'The fastest students are often those who recognise patterns early.', 133),
    ('pcm-motivation-135', 'Speed, Accuracy and Stamina', 'Timed practice trains the mind to decide, not merely calculate.', 134),
    ('pcm-motivation-136', 'Speed, Accuracy and Stamina', 'Stamina grows when focused sessions are extended gradually.', 135),
    ('pcm-motivation-137', 'Speed, Accuracy and Stamina', 'Do not practise only until you get the answer right; practise until the method you use to solve becomes reliable.', 136),
    ('pcm-motivation-138', 'Speed, Accuracy and Stamina', 'A quick calculation is valuable only when the sign, unit and logic are correct.', 137),
    ('pcm-motivation-139', 'Speed, Accuracy and Stamina', 'Speed improves when basic operations no longer consume mental energy.', 138),
    ('pcm-motivation-140', 'Speed, Accuracy and Stamina', 'One hour of uninterrupted problem-solving builds more stamina than several distracted hours.', 139),
    ('pcm-motivation-141', 'Speed, Accuracy and Stamina', 'Accuracy comes from organised steps, not from moving slowly.', 140),
    ('pcm-motivation-142', 'Speed, Accuracy and Stamina', 'Train yourself to remain careful during the final twenty minutes of a long paper.', 141),
    ('pcm-motivation-143', 'Speed, Accuracy and Stamina', 'Mental stamina is the ability to think clearly after the excitement of starting has disappeared.', 142),
    ('pcm-motivation-144', 'Speed, Accuracy and Stamina', 'Short daily timed tests build speed more safely than occasional rushed practice.', 143),
    ('pcm-motivation-145', 'Speed, Accuracy and Stamina', 'Use estimation to detect answers that are numerically possible but logically wrong.', 144),
    ('pcm-motivation-146', 'Speed, Accuracy and Stamina', 'Your rough work should save time, not create confusion.', 145),
    ('pcm-motivation-147', 'Speed, Accuracy and Stamina', 'A strong student can shift between fast recall and slow reasoning when required.', 146),
    ('pcm-motivation-148', 'Speed, Accuracy and Stamina', 'The aim is not to solve every question quickly; it is to spend the right time on each question till you master the method.', 147),
    ('pcm-motivation-149', 'Speed, Accuracy and Stamina', 'Accuracy under pressure is a skill developed through repeated pressure.', 148),
    ('pcm-motivation-150', 'Speed, Accuracy and Stamina', 'Exam stamina is built by completing full-length papers, not only short worksheets.', 149),
    ('pcm-motivation-151', 'Best Ways to Prepare', 'Prepare from the syllabus, practise from questions and improve from mistakes.', 150),
    ('pcm-motivation-152', 'Best Ways to Prepare', 'Begin preparation by identifying what is strong, weak and completely unfamiliar.', 151),
    ('pcm-motivation-153', 'Best Ways to Prepare', 'Study plans work best when each session has a specific output. Reflect on the day’s efforts.', 152),
    ('pcm-motivation-154', 'Best Ways to Prepare', 'Revise a concept on the same day, after a few days and again after a few weeks.', 153),
    ('pcm-motivation-155', 'Best Ways to Prepare', 'A formula sheet is useful only when it is regularly recalled without looking.', 154),
    ('pcm-motivation-156', 'Best Ways to Prepare', 'Practise chapter-wise first, mixed questions next and full papers last.', 155),
    ('pcm-motivation-157', 'Best Ways to Prepare', 'Prepare difficult chapters early enough to revisit them several times.', 156),
    ('pcm-motivation-158', 'Best Ways to Prepare', 'The best revision combines recall, problem-solving and error correction.', 157),
    ('pcm-motivation-159', 'Best Ways to Prepare', 'Do not spend equal time on every chapter; spend time according to importance and weakness.', 158),
    ('pcm-motivation-160', 'Best Ways to Prepare', 'Previous-year questions reveal how familiar concepts are converted into examination problems.', 159),
    ('pcm-motivation-161', 'Best Ways to Prepare', 'Create an error notebook containing wrong formulas, missed conditions and repeated calculation mistakes.', 160),
    ('pcm-motivation-162', 'Best Ways to Prepare', 'Prepare for the paper you must write, not only for the chapter you enjoy studying.', 161),
    ('pcm-motivation-163', 'Best Ways to Prepare', 'Use short breaks to refresh attention, not to enter another long distraction.', 162),
    ('pcm-motivation-164', 'Best Ways to Prepare', 'Every study session should end with a quick test of what you can recall.', 163),
    ('pcm-motivation-165', 'Best Ways to Prepare', 'Practise quiz questions without notes before assuming that a chapter is complete.', 164),
    ('pcm-motivation-166', 'Best Ways to Prepare', 'Strong preparation moves from understanding to practice, from practice to testing and from testing to correction.', 165),
    ('pcm-motivation-167', 'Best Ways to Prepare', 'Complete the most important topics first; perfection in one chapter cannot compensate for ignoring five others.', 166),
    ('pcm-motivation-168', 'Best Ways to Prepare', 'Simulate examination conditions before examination day becomes your first full simulation.', 167),
    ('pcm-motivation-169', 'Best Ways to Prepare', 'The best preparation leaves fewer surprises—not because you know every question, but because you can handle unfamiliar ones.', 168),
    ('pcm-motivation-170', 'Mindset on Exam Day', 'Enter the examination hall to execute your preparation, not to judge your future.', 169),
    ('pcm-motivation-171', 'Mindset on Exam Day', 'A calm first five minutes can protect the next three hours.', 170),
    ('pcm-motivation-172', 'Mindset on Exam Day', 'Read the entire paper with curiosity, not fear. Fear makes you confused', 171),
    ('pcm-motivation-173', 'Mindset on Exam Day', 'Begin with confidence, continue with discipline and finish with verification.', 172),
    ('pcm-motivation-174', 'Mindset on Exam Day', 'Do not decide that a paper is difficult before you have identified the questions you can solve.', 173),
    ('pcm-motivation-175', 'Mindset on Exam Day', 'One challenging section does not define the whole examination.', 174),
    ('pcm-motivation-176', 'Mindset on Exam Day', 'Your task is not to know everything; it is to earn every mark available from what you know.', 175),
    ('pcm-motivation-177', 'Mindset on Exam Day', 'Breathe deep before reacting to an unfamiliar question.', 176),
    ('pcm-motivation-178', 'Mindset on Exam Day', 'On exam day, trust your preparation more than your anxiety.', 177),
    ('pcm-motivation-179', 'Mindset on Exam Day', 'Do not borrow panic from students discussing answers outside the examination hall.', 178),
    ('pcm-motivation-180', 'Mindset on Exam Day', 'Keep moving when stuck; returning with a calmer mind often reveals the method.', 179),
    ('pcm-motivation-181', 'Mindset on Exam Day', 'Check signs, units, question numbers and final answers before submitting.', 180),
    ('pcm-motivation-182', 'Mindset on Exam Day', 'A temporary blank mind is a signal to pause, breathe and retrieve—not to panic.', 181),
    ('pcm-motivation-183', 'Mindset on Exam Day', 'Save enough time to review the answers that carry the most marks.', 182),
    ('pcm-motivation-184', 'Mindset on Exam Day', 'Leave the examination hall with lessons, not endless rechecking of what cannot be changed. This will help you prepare for your next exam day', 183),
    ('pcm-motivation-185', 'Mindset on Exam Day', 'The best exam-day mindset is simple: one question, one decision and one careful step at a time.', 184)
)
INSERT INTO public.edubite_inspiration_quotes (
  content_key,
  category,
  quote,
  sort_order
)
SELECT content_key, category, quote, sort_order
FROM catalog
ON CONFLICT (content_key) DO UPDATE
SET category = EXCLUDED.category,
    quote = EXCLUDED.quote,
    sort_order = EXCLUDED.sort_order;

DELETE FROM public.edubite_inspiration_quotes
WHERE content_key NOT IN ('pcm-motivation-001', 'pcm-motivation-002', 'pcm-motivation-003', 'pcm-motivation-004', 'pcm-motivation-005', 'pcm-motivation-006', 'pcm-motivation-007', 'pcm-motivation-008', 'pcm-motivation-009', 'pcm-motivation-010', 'pcm-motivation-011', 'pcm-motivation-012', 'pcm-motivation-013', 'pcm-motivation-014', 'pcm-motivation-015', 'pcm-motivation-016', 'pcm-motivation-017', 'pcm-motivation-018', 'pcm-motivation-019', 'pcm-motivation-020', 'pcm-motivation-021', 'pcm-motivation-022', 'pcm-motivation-023', 'pcm-motivation-024', 'pcm-motivation-025', 'pcm-motivation-026', 'pcm-motivation-027', 'pcm-motivation-028', 'pcm-motivation-029', 'pcm-motivation-030', 'pcm-motivation-031', 'pcm-motivation-032', 'pcm-motivation-033', 'pcm-motivation-034', 'pcm-motivation-035', 'pcm-motivation-036', 'pcm-motivation-037', 'pcm-motivation-038', 'pcm-motivation-039', 'pcm-motivation-040', 'pcm-motivation-041', 'pcm-motivation-042', 'pcm-motivation-043', 'pcm-motivation-044', 'pcm-motivation-045', 'pcm-motivation-046', 'pcm-motivation-047', 'pcm-motivation-048', 'pcm-motivation-049', 'pcm-motivation-050', 'pcm-motivation-051', 'pcm-motivation-052', 'pcm-motivation-053', 'pcm-motivation-054', 'pcm-motivation-055', 'pcm-motivation-056', 'pcm-motivation-057', 'pcm-motivation-058', 'pcm-motivation-059', 'pcm-motivation-060', 'pcm-motivation-061', 'pcm-motivation-062', 'pcm-motivation-063', 'pcm-motivation-064', 'pcm-motivation-065', 'pcm-motivation-066', 'pcm-motivation-067', 'pcm-motivation-068', 'pcm-motivation-069', 'pcm-motivation-070', 'pcm-motivation-071', 'pcm-motivation-072', 'pcm-motivation-073', 'pcm-motivation-074', 'pcm-motivation-075', 'pcm-motivation-076', 'pcm-motivation-077', 'pcm-motivation-078', 'pcm-motivation-079', 'pcm-motivation-080', 'pcm-motivation-081', 'pcm-motivation-082', 'pcm-motivation-083', 'pcm-motivation-084', 'pcm-motivation-085', 'pcm-motivation-086', 'pcm-motivation-087', 'pcm-motivation-088', 'pcm-motivation-089', 'pcm-motivation-090', 'pcm-motivation-091', 'pcm-motivation-092', 'pcm-motivation-093', 'pcm-motivation-094', 'pcm-motivation-095', 'pcm-motivation-096', 'pcm-motivation-097', 'pcm-motivation-098', 'pcm-motivation-099', 'pcm-motivation-100', 'pcm-motivation-101', 'pcm-motivation-102', 'pcm-motivation-103', 'pcm-motivation-104', 'pcm-motivation-105', 'pcm-motivation-106', 'pcm-motivation-107', 'pcm-motivation-108', 'pcm-motivation-109', 'pcm-motivation-110', 'pcm-motivation-111', 'pcm-motivation-112', 'pcm-motivation-113', 'pcm-motivation-114', 'pcm-motivation-115', 'pcm-motivation-116', 'pcm-motivation-117', 'pcm-motivation-118', 'pcm-motivation-119', 'pcm-motivation-120', 'pcm-motivation-121', 'pcm-motivation-122', 'pcm-motivation-123', 'pcm-motivation-124', 'pcm-motivation-125', 'pcm-motivation-126', 'pcm-motivation-127', 'pcm-motivation-128', 'pcm-motivation-129', 'pcm-motivation-130', 'pcm-motivation-131', 'pcm-motivation-132', 'pcm-motivation-133', 'pcm-motivation-134', 'pcm-motivation-135', 'pcm-motivation-136', 'pcm-motivation-137', 'pcm-motivation-138', 'pcm-motivation-139', 'pcm-motivation-140', 'pcm-motivation-141', 'pcm-motivation-142', 'pcm-motivation-143', 'pcm-motivation-144', 'pcm-motivation-145', 'pcm-motivation-146', 'pcm-motivation-147', 'pcm-motivation-148', 'pcm-motivation-149', 'pcm-motivation-150', 'pcm-motivation-151', 'pcm-motivation-152', 'pcm-motivation-153', 'pcm-motivation-154', 'pcm-motivation-155', 'pcm-motivation-156', 'pcm-motivation-157', 'pcm-motivation-158', 'pcm-motivation-159', 'pcm-motivation-160', 'pcm-motivation-161', 'pcm-motivation-162', 'pcm-motivation-163', 'pcm-motivation-164', 'pcm-motivation-165', 'pcm-motivation-166', 'pcm-motivation-167', 'pcm-motivation-168', 'pcm-motivation-169', 'pcm-motivation-170', 'pcm-motivation-171', 'pcm-motivation-172', 'pcm-motivation-173', 'pcm-motivation-174', 'pcm-motivation-175', 'pcm-motivation-176', 'pcm-motivation-177', 'pcm-motivation-178', 'pcm-motivation-179', 'pcm-motivation-180', 'pcm-motivation-181', 'pcm-motivation-182', 'pcm-motivation-183', 'pcm-motivation-184', 'pcm-motivation-185');

ALTER TABLE public.edubite_inspiration_quotes
  ALTER COLUMN content_key SET NOT NULL;

GRANT SELECT ON public.edubite_inspiration_quotes TO anon, authenticated;

COMMIT;
